version: 2
project_name: gh-enhance

# Build settings
builds:
  - binary: gh-enhance
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Archive format for releases
archives:
  - formats:
      - binary
    name_template: "gh-enhance_{{ .Tag }}_{{ .Os }}-{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"


# Release settings
release:
  github:
    owner: shashankgroovy
    name: gh-enhance
  # Draft and prerelease flags are now top-level in release
  draft: false
  prerelease: false

# Changelog generation
changelog:
  use: git